export const API_BASE_URL = 'https://fantasy.premierleague.com/api/'
export const API_URLS = {
  FIXTURES: 'fixtures/',
  GAMEWEEKS: 'events/',
  GAMEWEEK_FIXTURES: 'fixtures/?event={}',
  GAMEWEEK_LIVE: 'event/{}/live',
  LEAGUE_CLASSIC: 'leagues-classic/{}/standings/',
  LEAGUE_H2H: 'leagues-h2h/{}/standings/',
  LEAGUE_H2H_FIXTURES: 'leagues-h2h-matches/league/{}/?{}page={}',
  PLAYER_SUMMARY: 'element-summary/{}/',
  SETTINGS: 'game-settings/',
  STATIC: 'bootstrap-static/',
  TEAMS: 'teams/',
  TRANSFERS: 'transfers/',
  USER: 'entry/{}/',
  USER_CUP: 'entry/{}/cup/',
  USER_HISTORY: 'entry/{}/history/',
  USER_PICKS: 'entry/{}/event/{}/picks/',
  USER_TEAM: 'my-team/{}/',
  USER_TRANSFERS: 'entry/{}/transfers/',
  USER_LATEST_TRANSFERS: 'entry/{}/transfers-latest/',
  WATCHLIST: 'watchlist/',
  ME: 'me/',
}
