name: Test and release

# Run the workflow when a Pull Request is opened or when changes are pushed to main
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Fetch the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js using the appropriate version
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install package dependencies
      - name: Install root lib deps
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      # Run tests
      # - name: Test
      #  run: npm test

      - name: Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build

  release:
    # Only release on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next'
    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
